export interface CAFAssessmentQuestion {
  id: string;
  outcomeId: string;
  outcomeName: string;
  principleId: string;
  principleName: string;
  objectiveId: string;
  objectiveName: string;
  question: string;
  isNegative: boolean; // true if answering "yes" indicates non-compliance
  section?: "negative" | "partial" | "achieved"; // section type
}

export const CAF_ASSESSMENT_QUESTIONS: CAFAssessmentQuestion[] = [
  // OBJECTIVE A - Managing Security Risk
  // A1 Governance
  {
    id: "A1.a.1",
    outcomeId: "A1.a",
    outcomeName: "Board Direction",
    principleId: "A1",
    principleName: "Governance",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Is the security of network and information systems related to the operation of essential function(s) NOT discussed or reported on regularly at board-level?",
    isNegative: true,
    section: "negative",
  },
  {
    id: "A1.a.2",
    outcomeId: "A1.a",
    outcomeName: "Board Direction",
    principleId: "A1",
    principleName: "Governance",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Are board-level discussions on the security of network and information systems based on partial or out-of-date information, without the benefit of expert guidance?",
    isNegative: true,
    section: "negative",
  },
  {
    id: "A1.a.3",
    outcomeId: "A1.a",
    outcomeName: "Board Direction",
    principleId: "A1",
    principleName: "Governance",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Are the security of network and information systems supporting your essential function(s) NOT driven effectively by the direction set at board-level?",
    isNegative: true,
    section: "negative",
  },
  {
    id: "A1.a.4",
    outcomeId: "A1.a",
    outcomeName: "Board Direction",
    principleId: "A1",
    principleName: "Governance",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Do senior management or other pockets of the organisation consider themselves exempt from some policies or expect special accommodations to be made?",
    isNegative: true,
    section: "negative",
  },
  {
    id: "A1.b.1",
    outcomeId: "A1.b",
    outcomeName: "Roles and Responsibilities",
    principleId: "A1",
    principleName: "Governance",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Are key roles missing, left vacant, or fulfilled on an ad-hoc or informal basis?",
    isNegative: true,
    section: "negative",
  },
  {
    id: "A1.b.2",
    outcomeId: "A1.b",
    outcomeName: "Roles and Responsibilities",
    principleId: "A1",
    principleName: "Governance",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Are staff assigned security responsibilities but without adequate authority or resources to fulfil them?",
    isNegative: true,
    section: "negative",
  },
  {
    id: "A1.b.3",
    outcomeId: "A1.b",
    outcomeName: "Roles and Responsibilities",
    principleId: "A1",
    principleName: "Governance",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Are staff unsure what their responsibilities are for the security of the essential function(s)?",
    isNegative: true,
    section: "negative",
  },
  {
    id: "A1.c.1",
    outcomeId: "A1.c",
    outcomeName: "Decision-making",
    principleId: "A1",
    principleName: "Governance",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Are relatively straightforward risk decisions constantly referred up the chain, or not made?",
    isNegative: true,
    section: "negative",
  },
  {
    id: "A1.c.2",
    outcomeId: "A1.c",
    outcomeName: "Decision-making",
    principleId: "A1",
    principleName: "Governance",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Are risks resolved informally (or ignored) at a local level when the use of a more formal risk reporting mechanism would be more appropriate?",
    isNegative: true,
    section: "negative",
  },
  {
    id: "A1.c.3",
    outcomeId: "A1.c",
    outcomeName: "Decision-making",
    principleId: "A1",
    principleName: "Governance",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Are decision-makers unsure of what senior management's risk appetite is, or only understand it in vague terms such as 'averse' or 'cautious'?",
    isNegative: true,
    section: "negative",
  },
  {
    id: "A1.c.4",
    outcomeId: "A1.c",
    outcomeName: "Decision-making",
    principleId: "A1",
    principleName: "Governance",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Are decision-makers unable to justify their risk management decisions?",
    isNegative: true,
    section: "negative",
  },
  {
    id: "A1.c.5",
    outcomeId: "A1.c",
    outcomeName: "Decision-making",
    principleId: "A1",
    principleName: "Governance",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Does organisational structure cause risk decisions to be made in isolation (e.g. engineering and IT don't talk to each other about risk)?",
    isNegative: true,
    section: "negative",
  },
  {
    id: "A1.c.6",
    outcomeId: "A1.c",
    outcomeName: "Decision-making",
    principleId: "A1",
    principleName: "Governance",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Are risk priorities too vague to make meaningful distinctions between them (e.g. almost all risks are rated 'medium' or 'amber')?",
    isNegative: true,
    section: "negative",
  },

  // A2 Risk Management
  {
    id: "A2.a.1",
    outcomeId: "A2.a",
    outcomeName: "Risk Management Process",
    principleId: "A2",
    principleName: "Risk Management",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Is there no systematic process in place to ensure that identified security risks are managed effectively?",
    isNegative: true,
    section: "negative",
  },
  {
    id: "A2.a.2",
    outcomeId: "A2.a",
    outcomeName: "Risk Management Process",
    principleId: "A2",
    principleName: "Risk Management",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Are systems assessed in isolation, without consideration of dependencies and interactions with other systems (e.g. interactions between IT and OT environments)?",
    isNegative: true,
    section: "negative",
  },
  {
    id: "A2.a.3",
    outcomeId: "A2.a",
    outcomeName: "Risk Management Process",
    principleId: "A2",
    principleName: "Risk Management",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Are security requirements and mitigations arbitrary or are applied from a control catalogue without consideration of how they contribute to the security of network and information systems?",
    isNegative: true,
    section: "negative",
  },
  {
    id: "A2.a.4",
    outcomeId: "A2.a",
    outcomeName: "Risk Management Process",
    principleId: "A2",
    principleName: "Risk Management",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Do risks remain unresolved on a register for prolonged periods of time awaiting senior decision-making or resource allocation to resolve?",
    isNegative: true,
    section: "negative",
  },
  {
    id: "A2.b.1",
    outcomeId: "A2.b",
    outcomeName: "Understanding Threat",
    principleId: "A2",
    principleName: "Risk Management",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Are you unable to perform threat analysis?",
    isNegative: true,
    section: "negative",
  },
  {
    id: "A2.b.2",
    outcomeId: "A2.b",
    outcomeName: "Understanding Threat",
    principleId: "A2",
    principleName: "Risk Management",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Do you not understand the threats to network and information systems supporting your essential function(s)?",
    isNegative: true,
    section: "negative",
  },
  {
    id: "A2.b.3",
    outcomeId: "A2.b",
    outcomeName: "Understanding Threat",
    principleId: "A2",
    principleName: "Risk Management",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Do you not have a clearly defined set of threat assumptions?",
    isNegative: true,
    section: "negative",
  },
  {
    id: "A2.c.1",
    outcomeId: "A2.c",
    outcomeName: "Assurance",
    principleId: "A2",
    principleName: "Risk Management",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Is a particular product or service seen as a 'silver bullet' and vendor claims are taken at face value?",
    isNegative: true,
    section: "negative",
  },
  {
    id: "A2.c.2",
    outcomeId: "A2.c",
    outcomeName: "Assurance",
    principleId: "A2",
    principleName: "Risk Management",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Are assurance methods applied without appreciation of their strengths and limitations?",
    isNegative: true,
    section: "negative",
  },
  {
    id: "A2.c.3",
    outcomeId: "A2.c",
    outcomeName: "Assurance",
    principleId: "A2",
    principleName: "Risk Management",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Is assurance assumed because there have been no known problems to date?",
    isNegative: true,
    section: "negative",
  },

  // A3 Asset Management
  {
    id: "A3.a.1",
    outcomeId: "A3.a",
    outcomeName: "Asset Management",
    principleId: "A3",
    principleName: "Asset Management",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Are inventories of assets relevant to network and information systems supporting your essential function(s) incomplete, non-existent or inadequately detailed?",
    isNegative: true,
  },
  {
    id: "A3.a.2",
    outcomeId: "A3.a",
    outcomeName: "Asset Management",
    principleId: "A3",
    principleName: "Asset Management",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Are only certain domains or types of asset documented and understood?",
    isNegative: true,
  },
  {
    id: "A3.a.3",
    outcomeId: "A3.a",
    outcomeName: "Asset Management",
    principleId: "A3",
    principleName: "Asset Management",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Are dependencies between assets not understood (such as the dependencies between IT and OT)?",
    isNegative: true,
  },
  {
    id: "A3.a.4",
    outcomeId: "A3.a",
    outcomeName: "Asset Management",
    principleId: "A3",
    principleName: "Asset Management",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Are information assets stored for long periods of time with no clear business need or retention policy?",
    isNegative: true,
  },
  {
    id: "A3.a.5",
    outcomeId: "A3.a",
    outcomeName: "Asset Management",
    principleId: "A3",
    principleName: "Asset Management",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Is knowledge critical to the management, operation, or recovery of network and information systems held by one or two key individuals with no succession plan?",
    isNegative: true,
  },
  {
    id: "A3.a.6",
    outcomeId: "A3.a",
    outcomeName: "Asset Management",
    principleId: "A3",
    principleName: "Asset Management",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Are asset inventories neglected and out of date?",
    isNegative: true,
  },

  // A4 Supply Chain
  {
    id: "A4.a.1",
    outcomeId: "A4.a",
    outcomeName: "Supply Chain",
    principleId: "A4",
    principleName: "Supply Chain",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Do you not know what data belonging to you is held by suppliers, or how it is managed?",
    isNegative: true,
  },
  {
    id: "A4.a.2",
    outcomeId: "A4.a",
    outcomeName: "Supply Chain",
    principleId: "A4",
    principleName: "Supply Chain",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Are elements of the supply chain for network and information systems subcontracted and you have little or no visibility of the sub-contractors?",
    isNegative: true,
  },
  {
    id: "A4.a.3",
    outcomeId: "A4.a",
    outcomeName: "Supply Chain",
    principleId: "A4",
    principleName: "Supply Chain",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Do you have no understanding of which contracts are relevant and/or relevant contracts do not specify appropriate security obligations?",
    isNegative: true,
  },

  // OBJECTIVE B - Protecting Against Cyber Attack
  // B1 Service Protection Policies, Processes and Procedures
  {
    id: "B1.a.1",
    outcomeId: "B1.a",
    outcomeName: "Policy, Process and Procedure Development",
    principleId: "B1",
    principleName: "Service Protection Policies and Procedures",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Are your policies, processes and procedures absent or incomplete?",
    isNegative: true,
  },
  {
    id: "B1.a.2",
    outcomeId: "B1.a",
    outcomeName: "Policy, Process and Procedure Development",
    principleId: "B1",
    principleName: "Service Protection Policies and Procedures",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Are policies, processes and procedures not applied universally or consistently?",
    isNegative: true,
  },
  {
    id: "B1.a.3",
    outcomeId: "B1.a",
    outcomeName: "Policy, Process and Procedure Development",
    principleId: "B1",
    principleName: "Service Protection Policies and Procedures",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Is system security totally reliant on users' careful and consistent application of manual security processes?",
    isNegative: true,
  },
  {
    id: "B1.a.4",
    outcomeId: "B1.a",
    outcomeName: "Policy, Process and Procedure Development",
    principleId: "B1",
    principleName: "Service Protection Policies and Procedures",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Have policies, processes and procedures not been reviewed in response to major changes or within a suitable period?",
    isNegative: true,
  },
  {
    id: "B1.b.1",
    outcomeId: "B1.b",
    outcomeName: "Policy, Process and Procedure Implementation",
    principleId: "B1",
    principleName: "Service Protection Policies and Procedures",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Are policies, processes and procedures ignored or only partially followed?",
    isNegative: true,
  },
  {
    id: "B1.b.2",
    outcomeId: "B1.b",
    outcomeName: "Policy, Process and Procedure Implementation",
    principleId: "B1",
    principleName: "Service Protection Policies and Procedures",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Is how your policies, processes and procedures support the resilience of your essential function(s) not well understood?",
    isNegative: true,
  },
  {
    id: "B1.b.3",
    outcomeId: "B1.b",
    outcomeName: "Policy, Process and Procedure Implementation",
    principleId: "B1",
    principleName: "Service Protection Policies and Procedures",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Are staff unaware of their responsibilities under your policies, processes and procedures?",
    isNegative: true,
  },
  {
    id: "B1.b.4",
    outcomeId: "B1.b",
    outcomeName: "Policy, Process and Procedure Implementation",
    principleId: "B1",
    principleName: "Service Protection Policies and Procedures",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Do policies, processes and procedures lack integration with other organisational policies, processes and procedures?",
    isNegative: true,
  },

  // B2 Identity and Access Control
  {
    id: "B2.a.1",
    outcomeId: "B2.a",
    outcomeName: "Identity Verification, Authentication and Authorisation",
    principleId: "B2",
    principleName: "Identity and Access Control",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Is initial identity verification not robust enough to provide an acceptable level of confidence of a user's identity profile?",
    isNegative: true,
  },
  {
    id: "B2.a.2",
    outcomeId: "B2.a",
    outcomeName: "Identity Verification, Authentication and Authorisation",
    principleId: "B2",
    principleName: "Identity and Access Control",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Can authorised users and systems with access to networks or information systems on which your essential function(s) depends NOT be individually identified?",
    isNegative: true,
  },
  {
    id: "B2.a.3",
    outcomeId: "B2.a",
    outcomeName: "Identity Verification, Authentication and Authorisation",
    principleId: "B2",
    principleName: "Identity and Access Control",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Can unauthorised individuals or devices access your network or information systems on which your essential function(s) depends?",
    isNegative: true,
  },
  {
    id: "B2.a.4",
    outcomeId: "B2.a",
    outcomeName: "Identity Verification, Authentication and Authorisation",
    principleId: "B2",
    principleName: "Identity and Access Control",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Is the number of authorised users and systems that have access to network and information systems NOT limited to the minimum?",
    isNegative: true,
  },
  {
    id: "B2.a.5",
    outcomeId: "B2.a",
    outcomeName: "Identity Verification, Authentication and Authorisation",
    principleId: "B2",
    principleName: "Identity and Access Control",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Does your approach to authenticating users, devices and systems not follow up to date best practice?",
    isNegative: true,
  },
  {
    id: "B2.d.1",
    outcomeId: "B2.d",
    outcomeName: "Identity and Access Management (IdAM)",
    principleId: "B2",
    principleName: "Identity and Access Control",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Are greater access rights granted than necessary?",
    isNegative: true,
  },
  {
    id: "B2.d.2",
    outcomeId: "B2.d",
    outcomeName: "Identity and Access Management (IdAM)",
    principleId: "B2",
    principleName: "Identity and Access Control",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Is identity validation and requirement for access of a user, device or systems not carried out?",
    isNegative: true,
  },
  {
    id: "B2.d.3",
    outcomeId: "B2.d",
    outcomeName: "Identity and Access Management (IdAM)",
    principleId: "B2",
    principleName: "Identity and Access Control",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Are user access rights not reviewed when users change roles?",
    isNegative: true,
  },

  // B3 Data Security
  {
    id: "B3.a.1",
    outcomeId: "B3.a",
    outcomeName: "Understanding Data",
    principleId: "B3",
    principleName: "Data Security",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Do you have incomplete knowledge of what data is used by and produced in the operation of network and information systems supporting your essential function(s)?",
    isNegative: true,
  },
  {
    id: "B3.a.2",
    outcomeId: "B3.a",
    outcomeName: "Understanding Data",
    principleId: "B3",
    principleName: "Data Security",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Have you not identified the important data on which network and information systems supporting your essential function(s) relies?",
    isNegative: true,
  },
  {
    id: "B3.a.3",
    outcomeId: "B3.a",
    outcomeName: "Understanding Data",
    principleId: "B3",
    principleName: "Data Security",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Have you not identified who has access to data important to the operation of network and information systems supporting your essential function(s)?",
    isNegative: true,
  },
  {
    id: "B3.a.4",
    outcomeId: "B3.a",
    outcomeName: "Understanding Data",
    principleId: "B3",
    principleName: "Data Security",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Have you not clearly articulated the impact of data compromise or lack of availability of network and information systems supporting your essential function(s)?",
    isNegative: true,
  },
  {
    id: "B3.b.1",
    outcomeId: "B3.b",
    outcomeName: "Data in Transit",
    principleId: "B3",
    principleName: "Data Security",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Do you not know what all your data links are, or which carry data important to the operation of the essential function(s)?",
    isNegative: true,
  },
  {
    id: "B3.b.2",
    outcomeId: "B3.b",
    outcomeName: "Data in Transit",
    principleId: "B3",
    principleName: "Data Security",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Does data important to the operation of the essential function(s) travel without technical protection over non-trusted or openly accessible carriers?",
    isNegative: true,
  },
  {
    id: "B3.b.3",
    outcomeId: "B3.b",
    outcomeName: "Data in Transit",
    principleId: "B3",
    principleName: "Data Security",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Do critical data paths that could fail, be jammed, be overloaded, etc. have no alternative path?",
    isNegative: true,
  },
  {
    id: "B3.c.1",
    outcomeId: "B3.c",
    outcomeName: "Stored Data",
    principleId: "B3",
    principleName: "Data Security",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Do you have no, or limited, knowledge of where data important to the operation of network and information systems supporting your essential function(s) is stored?",
    isNegative: true,
  },
  {
    id: "B3.c.2",
    outcomeId: "B3.c",
    outcomeName: "Stored Data",
    principleId: "B3",
    principleName: "Data Security",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Have you not protected vulnerable stored data important to the operation of network and information systems supporting your essential function(s) in a suitable way?",
    isNegative: true,
  },

  // B4 System Security
  {
    id: "B4.b.1",
    outcomeId: "B4.b",
    outcomeName: "Secure Configuration",
    principleId: "B4",
    principleName: "System Security",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Have you not identified the assets that need to be carefully configured to maintain the security of network and information systems supporting your essential function(s)?",
    isNegative: true,
  },
  {
    id: "B4.b.2",
    outcomeId: "B4.b",
    outcomeName: "Secure Configuration",
    principleId: "B4",
    principleName: "System Security",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Are policies relating to the security of operating system builds or configuration not applied consistently across network and information systems?",
    isNegative: true,
  },
  {
    id: "B4.b.3",
    outcomeId: "B4.b",
    outcomeName: "Secure Configuration",
    principleId: "B4",
    principleName: "System Security",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Is the recording of security changes or adjustments that affect your essential function(s) lacking or inconsistent?",
    isNegative: true,
  },
  {
    id: "B4.b.4",
    outcomeId: "B4.b",
    outcomeName: "Secure Configuration",
    principleId: "B4",
    principleName: "System Security",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Have generic, shared, default name and built-in accounts not been removed or disabled?",
    isNegative: true,
  },
  {
    id: "B4.b.5",
    outcomeId: "B4.b",
    outcomeName: "Secure Configuration",
    principleId: "B4",
    principleName: "System Security",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Are standard users able to change settings that would adversely impact the security of network and information systems supporting your essential function(s)?",
    isNegative: true,
  },
  {
    id: "B4.c.1",
    outcomeId: "B4.c",
    outcomeName: "Secure Management",
    principleId: "B4",
    principleName: "System Security",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Are your systems and devices supporting the operation of the essential function(s) administered or maintained from devices that are not corporately owned and managed?",
    isNegative: true,
  },
  {
    id: "B4.c.2",
    outcomeId: "B4.c",
    outcomeName: "Secure Management",
    principleId: "B4",
    principleName: "System Security",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Do you not have good or current technical documentation of network and information systems?",
    isNegative: true,
  },
  {
    id: "B4.d.1",
    outcomeId: "B4.d",
    outcomeName: "Vulnerability Management",
    principleId: "B4",
    principleName: "System Security",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Do you not understand the exposure of network and information systems supporting your essential function(s) to publicly-known vulnerabilities?",
    isNegative: true,
  },
  {
    id: "B4.d.2",
    outcomeId: "B4.d",
    outcomeName: "Vulnerability Management",
    principleId: "B4",
    principleName: "System Security",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Do you not mitigate externally exposed vulnerabilities promptly?",
    isNegative: true,
  },
  {
    id: "B4.d.3",
    outcomeId: "B4.d",
    outcomeName: "Vulnerability Management",
    principleId: "B4",
    principleName: "System Security",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Have you not recently tested to verify your understanding of the vulnerabilities of network and information systems that support your essential function(s)?",
    isNegative: true,
  },
  {
    id: "B4.d.4",
    outcomeId: "B4.d",
    outcomeName: "Vulnerability Management",
    principleId: "B4",
    principleName: "System Security",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Have you not suitably mitigated systems or software that is no longer supported?",
    isNegative: true,
  },
  {
    id: "B4.d.5",
    outcomeId: "B4.d",
    outcomeName: "Vulnerability Management",
    principleId: "B4",
    principleName: "System Security",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Are you not pursuing replacement for unsupported systems or software?",
    isNegative: true,
  },

  // B5 Resilient Networks and Systems
  {
    id: "B5.a.1",
    outcomeId: "B5.a",
    outcomeName: "Resilience Preparation",
    principleId: "B5",
    principleName: "Resilient Networks and Systems",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Do you have limited understanding of all the elements that are required to restore operation of network and information systems supporting your essential function(s)?",
    isNegative: true,
  },
  {
    id: "B5.a.2",
    outcomeId: "B5.a",
    outcomeName: "Resilience Preparation",
    principleId: "B5",
    principleName: "Resilient Networks and Systems",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Have you not completed business continuity and disaster recovery plans for network and information systems, including their dependencies, supporting the operation of the essential function(s)?",
    isNegative: true,
  },
  {
    id: "B5.b.1",
    outcomeId: "B5.b",
    outcomeName: "Design for Resilience",
    principleId: "B5",
    principleName: "Resilient Networks and Systems",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Are network and information systems supporting the operation of your essential function(s) not appropriately segregated?",
    isNegative: true,
  },
  {
    id: "B5.b.2",
    outcomeId: "B5.b",
    outcomeName: "Design for Resilience",
    principleId: "B5",
    principleName: "Resilient Networks and Systems",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Are internet services, such as browsing and email, accessible from network and information systems supporting your essential function(s)?",
    isNegative: true,
  },
  {
    id: "B5.b.3",
    outcomeId: "B5.b",
    outcomeName: "Design for Resilience",
    principleId: "B5",
    principleName: "Resilient Networks and Systems",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Do you not understand or lack plans to mitigate all resource limitations that could adversely affect your essential function(s)?",
    isNegative: true,
  },
  {
    id: "B5.c.1",
    outcomeId: "B5.c",
    outcomeName: "Backups",
    principleId: "B5",
    principleName: "Resilient Networks and Systems",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Is backup coverage incomplete and does not include all relevant data and information needed to restore the operation of your essential function(s)?",
    isNegative: true,
  },
  {
    id: "B5.c.2",
    outcomeId: "B5.c",
    outcomeName: "Backups",
    principleId: "B5",
    principleName: "Resilient Networks and Systems",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Are your comprehensive, automatic and tested technical and procedural backups NOT secured at centrally accessible or secondary sites to recover from an extreme event?",
    isNegative: true,
  },

  // B6 Staff Awareness and Training
  {
    id: "B6.a.1",
    outcomeId: "B6.a",
    outcomeName: "Cyber Security Culture",
    principleId: "B6",
    principleName: "Staff Awareness and Training",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Do people in your organisation not understand what they contribute to the cyber security of network and information systems supporting your essential function(s)?",
    isNegative: true,
  },
  {
    id: "B6.a.2",
    outcomeId: "B6.a",
    outcomeName: "Cyber Security Culture",
    principleId: "B6",
    principleName: "Staff Awareness and Training",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Do people in your organisation not know how to raise a concern about cyber security?",
    isNegative: true,
  },
  {
    id: "B6.a.3",
    outcomeId: "B6.a",
    outcomeName: "Cyber Security Culture",
    principleId: "B6",
    principleName: "Staff Awareness and Training",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Do people believe that reporting issues may get them into trouble?",
    isNegative: true,
  },
  {
    id: "B6.b.1",
    outcomeId: "B6.b",
    outcomeName: "Cyber Security Training",
    principleId: "B6",
    principleName: "Staff Awareness and Training",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Are there teams who operate and support your essential function(s) that lack any cyber security training?",
    isNegative: true,
  },
  {
    id: "B6.b.2",
    outcomeId: "B6.b",
    outcomeName: "Cyber Security Training",
    principleId: "B6",
    principleName: "Staff Awareness and Training",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Is cyber security training restricted to specific roles in your organisation?",
    isNegative: true,
  },
  {
    id: "B6.b.3",
    outcomeId: "B6.b",
    outcomeName: "Cyber Security Training",
    principleId: "B6",
    principleName: "Staff Awareness and Training",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Are cyber security training records for your organisation lacking or incomplete?",
    isNegative: true,
  },

  // OBJECTIVE C - Detecting Cyber Security Events
  // C1 Security Monitoring
  {
    id: "C1.a.1",
    outcomeId: "C1.a",
    outcomeName: "Sources and Tools for Logging and Monitoring",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Is data relating to the security and operation of network and information systems supporting your essential function(s) not collected?",
    isNegative: true,
  },
  {
    id: "C1.a.2",
    outcomeId: "C1.a",
    outcomeName: "Sources and Tools for Logging and Monitoring",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Are you not able to audit the activities of users and systems in relation to network and information systems supporting your essential function(s)?",
    isNegative: true,
  },
  {
    id: "C1.a.3",
    outcomeId: "C1.a",
    outcomeName: "Sources and Tools for Logging and Monitoring",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Do you not monitor traffic crossing your network boundary?",
    isNegative: true,
  },
  {
    id: "C1.a.4",
    outcomeId: "C1.a",
    outcomeName: "Sources and Tools for Logging and Monitoring",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Can log data not be synchronised using an accurate common time source?",
    isNegative: true,
  },
  {
    id: "C1.a.5",
    outcomeId: "C1.a",
    outcomeName: "Sources and Tools for Logging and Monitoring",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Are logs stored in locations where they are not readily available to authorised users and systems?",
    isNegative: true,
  },
  {
    id: "C1.a.6",
    outcomeId: "C1.a",
    outcomeName: "Sources and Tools for Logging and Monitoring",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Can your monitoring tools not be configured to make use of new log streams as they come online?",
    isNegative: true,
  },
  {
    id: "C1.a.7",
    outcomeId: "C1.a",
    outcomeName: "Sources and Tools for Logging and Monitoring",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Are your monitoring tools only able to make use of a fraction of the log data being collected?",
    isNegative: true,
  },
  {
    id: "C1.a.8",
    outcomeId: "C1.a",
    outcomeName: "Sources and Tools for Logging and Monitoring",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Do you not understand where log data is stored or how long it should be stored for?",
    isNegative: true,
  },
  {
    id: "C1.a.9",
    outcomeId: "C1.a",
    outcomeName: "Sources and Tools for Logging and Monitoring",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Do you have no way of ensuring log data is being captured as expected and available when needed?",
    isNegative: true,
  },
  {
    id: "C1.b.1",
    outcomeId: "C1.b",
    outcomeName: "Securing Logs",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Is it possible for log data to be easily edited or deleted by unauthorised users or malicious attackers?",
    isNegative: true,
  },
  {
    id: "C1.b.2",
    outcomeId: "C1.b",
    outcomeName: "Securing Logs",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Is there no controlled list of the users and systems that can view and query log data?",
    isNegative: true,
  },
  {
    id: "C1.b.3",
    outcomeId: "C1.b",
    outcomeName: "Securing Logs",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Is there no monitoring of the access to log data?",
    isNegative: true,
  },
  {
    id: "C1.b.4",
    outcomeId: "C1.b",
    outcomeName: "Securing Logs",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Are there no policies for accessing to log data?",
    isNegative: true,
  },
  {
    id: "C1.c.1",
    outcomeId: "C1.c",
    outcomeName: "Generating Alerts",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Do you not apply updates to your detection security technologies in a timely way, after receiving them (e.g. AV signature updates, other threat signatures or Indicators of Compromise)?",
    isNegative: true,
  },
  {
    id: "C1.c.2",
    outcomeId: "C1.c",
    outcomeName: "Generating Alerts",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Are security alerts relating to network and information systems supporting your essential function(s) not prioritised?",
    isNegative: true,
  },
  {
    id: "C1.c.3",
    outcomeId: "C1.c",
    outcomeName: "Generating Alerts",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Can the enrichment of security alerts within network and information systems supporting your essential function(s) not be performed?",
    isNegative: true,
  },
  {
    id: "C1.c.4",
    outcomeId: "C1.c",
    outcomeName: "Generating Alerts",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Do you not confidently detect the presence of IoCs on network and information systems supporting your essential function(s), such as known malicious command and control signatures?",
    isNegative: true,
  },
  {
    id: "C1.c.5",
    outcomeId: "C1.c",
    outcomeName: "Generating Alerts",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Do you not monitor for user or system abnormalities indicative of adverse activity?",
    isNegative: true,
  },
  {
    id: "C1.c.6",
    outcomeId: "C1.c",
    outcomeName: "Generating Alerts",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Are logs monitored infrequently?",
    isNegative: true,
  },
  {
    id: "C1.d.1",
    outcomeId: "C1.d",
    outcomeName: "Triage of Security Alerts",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Do you not triage alerts from your detection security technologies (e.g. AV, IDS)?",
    isNegative: true,
  },
  {
    id: "C1.d.2",
    outcomeId: "C1.d",
    outcomeName: "Triage of Security Alerts",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Do you not categorise alerts and incidents by type and priority/severity level?",
    isNegative: true,
  },
  {
    id: "C1.d.3",
    outcomeId: "C1.d",
    outcomeName: "Triage of Security Alerts",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Do you not have Standard Operating Procedures (SOPs)/Playbooks/Runbooks available for use during triage?",
    isNegative: true,
  },
  {
    id: "C1.d.4",
    outcomeId: "C1.d",
    outcomeName: "Triage of Security Alerts",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Do you not keep records of triage performed?",
    isNegative: true,
  },
  {
    id: "C1.d.5",
    outcomeId: "C1.d",
    outcomeName: "Triage of Security Alerts",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Do you not have a sufficient understanding of normal user or system behaviour to make effective decisions within triage?",
    isNegative: true,
  },
  {
    id: "C1.e.1",
    outcomeId: "C1.e",
    outcomeName: "Personnel Skills for Monitoring Tools and Detection",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Are there no personnel who perform a monitoring and detection function?",
    isNegative: true,
  },
  {
    id: "C1.e.2",
    outcomeId: "C1.e",
    outcomeName: "Personnel Skills for Monitoring Tools and Detection",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Do monitoring and detection personnel not have the correct specialist skills?",
    isNegative: true,
  },
  {
    id: "C1.e.3",
    outcomeId: "C1.e",
    outcomeName: "Personnel Skills for Monitoring Tools and Detection",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Are monitoring and detection personnel not capable of reporting against governance requirements?",
    isNegative: true,
  },
  {
    id: "C1.e.4",
    outcomeId: "C1.e",
    outcomeName: "Personnel Skills for Monitoring Tools and Detection",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Do monitoring and detection personnel have a lack of awareness of the essential function(s) the organisation provides and what assets relate to those functions?",
    isNegative: true,
  },
  {
    id: "C1.e.5",
    outcomeId: "C1.e",
    outcomeName: "Personnel Skills for Monitoring Tools and Detection",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Do monitoring and detection personnel have no awareness of other roles or tasks outside of security monitoring and detection that are relevant to the operation of your essential function(s)?",
    isNegative: true,
  },
  {
    id: "C1.e.6",
    outcomeId: "C1.e",
    outcomeName: "Personnel Skills for Monitoring Tools and Detection",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Are monitoring and detection personnel overwhelmed with the amount of data and alerts they have to work with, resulting in alert/triage fatigue?",
    isNegative: true,
  },
  {
    id: "C1.f.1",
    outcomeId: "C1.f",
    outcomeName: "Understanding User's and System's Behaviour, and Threat Intelligence",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Does your organisation have no sources of threat intelligence?",
    isNegative: true,
  },
  {
    id: "C1.f.2",
    outcomeId: "C1.f",
    outcomeName: "Understanding User's and System's Behaviour, and Threat Intelligence",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Do you not evaluate the usefulness of your threat intelligence or share feedback with providers or other users?",
    isNegative: true,
  },
  {
    id: "C1.f.3",
    outcomeId: "C1.f",
    outcomeName: "Understanding User's and System's Behaviour, and Threat Intelligence",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Do you have no awareness of the steps necessary to make best use of threat intelligence for security monitoring?",
    isNegative: true,
  },
  {
    id: "C1.f.4",
    outcomeId: "C1.f",
    outcomeName: "Understanding User's and System's Behaviour, and Threat Intelligence",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Is threat intelligence unreliable and/or is not actioned by the appropriate users or systems in a timely manner?",
    isNegative: true,
  },
  {
    id: "C1.f.5",
    outcomeId: "C1.f",
    outcomeName: "Understanding User's and System's Behaviour, and Threat Intelligence",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Do you have no established understanding of what abnormalities to look for that might signify adverse activities?",
    isNegative: true,
  },
  {
    id: "C1.f.6",
    outcomeId: "C1.f",
    outcomeName: "Understanding User's and System's Behaviour, and Threat Intelligence",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Do you not receive updates for all your detection security technologies (e.g. AV, IDS)?",
    isNegative: true,
  },
  {
    id: "C1.f.7",
    outcomeId: "C1.f",
    outcomeName: "Understanding User's and System's Behaviour, and Threat Intelligence",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Do you not understand normal user and system behaviour sufficiently to be able to use abnormalities to detect adverse activity?",
    isNegative: true,
  },

  // C2 Threat Hunting
  {
    id: "C2.a.1",
    outcomeId: "C2.a",
    outcomeName: "Threat Hunting",
    principleId: "C2",
    principleName: "Threat Hunting",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Do you not know the resources required for threat hunting?",
    isNegative: true,
  },
  {
    id: "C2.a.2",
    outcomeId: "C2.a",
    outcomeName: "Threat Hunting",
    principleId: "C2",
    principleName: "Threat Hunting",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Do you not have access to an effective threat hunting capability?",
    isNegative: true,
  },
  {
    id: "C2.a.3",
    outcomeId: "C2.a",
    outcomeName: "Threat Hunting",
    principleId: "C2",
    principleName: "Threat Hunting",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Do your threat hunts not follow any structure and few if any records are created?",
    isNegative: true,
  },

  // OBJECTIVE D - Minimising the Impact of Cyber Security Incidents
  // D1 Response and Recovery Planning
  {
    id: "D1.a.1",
    outcomeId: "D1.a",
    outcomeName: "Response Plan",
    principleId: "D1",
    principleName: "Response and Recovery Planning",
    objectiveId: "D",
    objectiveName: "Minimising the Impact of Cyber Security Incidents",
    question: "Is your incident response plan not documented?",
    isNegative: true,
  },
  {
    id: "D1.a.2",
    outcomeId: "D1.a",
    outcomeName: "Response Plan",
    principleId: "D1",
    principleName: "Response and Recovery Planning",
    objectiveId: "D",
    objectiveName: "Minimising the Impact of Cyber Security Incidents",
    question: "Does your incident response plan not include your organisation's identified essential function(s)?",
    isNegative: true,
  },
  {
    id: "D1.a.3",
    outcomeId: "D1.a",
    outcomeName: "Response Plan",
    principleId: "D1",
    principleName: "Response and Recovery Planning",
    objectiveId: "D",
    objectiveName: "Minimising the Impact of Cyber Security Incidents",
    question: "Is your incident response plan not well understood by relevant staff?",
    isNegative: true,
  },
  {
    id: "D1.b.1",
    outcomeId: "D1.b",
    outcomeName: "Response and Recovery Capability",
    principleId: "D1",
    principleName: "Response and Recovery Planning",
    objectiveId: "D",
    objectiveName: "Minimising the Impact of Cyber Security Incidents",
    question: "Have inadequate arrangements been made to make the right resources available to implement your response plan?",
    isNegative: true,
  },
  {
    id: "D1.b.2",
    outcomeId: "D1.b",
    outcomeName: "Response and Recovery Capability",
    principleId: "D1",
    principleName: "Response and Recovery Planning",
    objectiveId: "D",
    objectiveName: "Minimising the Impact of Cyber Security Incidents",
    question: "Are your response team members not equipped to make good response decisions and put them into effect?",
    isNegative: true,
  },
  {
    id: "D1.b.3",
    outcomeId: "D1.b",
    outcomeName: "Response and Recovery Capability",
    principleId: "D1",
    principleName: "Response and Recovery Planning",
    objectiveId: "D",
    objectiveName: "Minimising the Impact of Cyber Security Incidents",
    question: "Do inadequate back-up mechanisms exist to allow the continued operation of your essential function(s) during an incident?",
    isNegative: true,
  },
  {
    id: "D1.c.1",
    outcomeId: "D1.c",
    outcomeName: "Testing and Exercising",
    principleId: "D1",
    principleName: "Response and Recovery Planning",
    objectiveId: "D",
    objectiveName: "Minimising the Impact of Cyber Security Incidents",
    question: "Do exercises test only a discrete part of the process (e.g. that backups are working), but do not consider all areas?",
    isNegative: true,
  },
  {
    id: "D1.c.2",
    outcomeId: "D1.c",
    outcomeName: "Testing and Exercising",
    principleId: "D1",
    principleName: "Response and Recovery Planning",
    objectiveId: "D",
    objectiveName: "Minimising the Impact of Cyber Security Incidents",
    question: "Are incident response exercises not routinely carried out or are carried out in an ad-hoc way?",
    isNegative: true,
  },
  {
    id: "D1.c.3",
    outcomeId: "D1.c",
    outcomeName: "Testing and Exercising",
    principleId: "D1",
    principleName: "Response and Recovery Planning",
    objectiveId: "D",
    objectiveName: "Minimising the Impact of Cyber Security Incidents",
    question: "Are outputs from exercises not fed into the organisation's lessons learned process?",
    isNegative: true,
  },
  {
    id: "D1.c.4",
    outcomeId: "D1.c",
    outcomeName: "Testing and Exercising",
    principleId: "D1",
    principleName: "Response and Recovery Planning",
    objectiveId: "D",
    objectiveName: "Minimising the Impact of Cyber Security Incidents",
    question: "Do exercises not test all parts of the response cycle?",
    isNegative: true,
  },

  // D2 Lessons Learned
  {
    id: "D2.a.1",
    outcomeId: "D2.a",
    outcomeName: "Post Incident Analysis",
    principleId: "D2",
    principleName: "Lessons Learned",
    objectiveId: "D",
    objectiveName: "Minimising the Impact of Cyber Security Incidents",
    question: "Are you not usually able to resolve incidents to a root cause or identify the contributing factors within a broader systems context?",
    isNegative: true,
  },
  {
    id: "D2.a.2",
    outcomeId: "D2.a",
    outcomeName: "Post Incident Analysis",
    principleId: "D2",
    principleName: "Lessons Learned",
    objectiveId: "D",
    objectiveName: "Minimising the Impact of Cyber Security Incidents",
    question: "Do you not have a formal process for investigating causes?",
    isNegative: true,
  },
  {
    id: "D2.a.3",
    outcomeId: "D2.a",
    outcomeName: "Post Incident Analysis",
    principleId: "D2",
    principleName: "Lessons Learned",
    objectiveId: "D",
    objectiveName: "Minimising the Impact of Cyber Security Incidents",
    question: "Do investigators form theories early in the process and only seek evidence that affirms their belief?",
    isNegative: true,
  },
  {
    id: "D2.a.4",
    outcomeId: "D2.a",
    outcomeName: "Post Incident Analysis",
    principleId: "D2",
    principleName: "Lessons Learned",
    objectiveId: "D",
    objectiveName: "Minimising the Impact of Cyber Security Incidents",
    question: "Are investigations solely focused on identifying the person(s) who can be held responsible for the incident?",
    isNegative: true,
  },
  {
    id: "D2.b.1",
    outcomeId: "D2.b",
    outcomeName: "Using Incidents to Drive Improvements",
    principleId: "D2",
    principleName: "Lessons Learned",
    objectiveId: "D",
    objectiveName: "Minimising the Impact of Cyber Security Incidents",
    question: "Are improvements arising from lessons learned following an incident not implemented or not given sufficient organisational priority?",
    isNegative: true,
  },
  {
    id: "D2.b.2",
    outcomeId: "D2.b",
    outcomeName: "Using Incidents to Drive Improvements",
    principleId: "D2",
    principleName: "Lessons Learned",
    objectiveId: "D",
    objectiveName: "Minimising the Impact of Cyber Security Incidents",
    question: "Are changes made as a 'knee jerk' reaction to an incident without proper analysis and testing to ensure the change is appropriate?",
    isNegative: true,
  },
  {
    id: "D2.b.3",
    outcomeId: "D2.b",
    outcomeName: "Using Incidents to Drive Improvements",
    principleId: "D2",
    principleName: "Lessons Learned",
    objectiveId: "D",
    objectiveName: "Minimising the Impact of Cyber Security Incidents",
    question: "Do you wait until a severe or high-profile incident has occurred before you take steps to improve?",
    isNegative: true,
  },

  // PARTIALLY ACHIEVED QUESTIONS
  // OBJECTIVE A - Managing Security Risk
  {
    id: "A1.a.1-partial",
    outcomeId: "A1.a",
    outcomeName: "Board Direction",
    principleId: "A1",
    principleName: "Governance",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Are the security of network and information systems discussed at board-level at least quarterly?",
    isNegative: false,
    section: "partial",
  },
  {
    id: "A1.a.2-partial",
    outcomeId: "A1.a",
    outcomeName: "Board Direction",
    principleId: "A1",
    principleName: "Governance",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Does the board receive basic security reports, though they may lack comprehensive detail or expert analysis?",
    isNegative: false,
    section: "partial",
  },
  {
    id: "A1.b.1-partial",
    outcomeId: "A1.b",
    outcomeName: "Roles and Responsibilities",
    principleId: "A1",
    principleName: "Governance",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Are key security roles defined, even if not all positions are currently filled?",
    isNegative: false,
    section: "partial",
  },
  {
    id: "A1.c.1-partial",
    outcomeId: "A1.c",
    outcomeName: "Decision-making",
    principleId: "A1",
    principleName: "Governance",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Are risk decisions made with some formal process and basic documentation of rationale?",
    isNegative: false,
    section: "partial",
  },
  {
    id: "A2.a.1-partial",
    outcomeId: "A2.a",
    outcomeName: "Risk Management Process",
    principleId: "A2",
    principleName: "Risk Management",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Are security risks to essential functions identified and documented in some form?",
    isNegative: false,
    section: "partial",
  },
  {
    id: "A2.b.1-partial",
    outcomeId: "A2.b",
    outcomeName: "Understanding Threat",
    principleId: "A2",
    principleName: "Risk Management",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Is threat analysis performed to some degree, though it may not cover all threat scenarios?",
    isNegative: false,
    section: "partial",
  },
  {
    id: "A2.c.1-partial",
    outcomeId: "A2.c",
    outcomeName: "Assurance",
    principleId: "A2",
    principleName: "Risk Management",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Are basic assurance methods applied to validate security controls, though they may not be comprehensive?",
    isNegative: false,
    section: "partial",
  },
  {
    id: "A3.a.1-partial",
    outcomeId: "A3.a",
    outcomeName: "Asset Management",
    principleId: "A3",
    principleName: "Asset Management",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Are asset inventories maintained for key systems, though they may not be comprehensive or fully up to date?",
    isNegative: false,
    section: "partial",
  },
  {
    id: "A4.a.1-partial",
    outcomeId: "A4.a",
    outcomeName: "Supply Chain",
    principleId: "A4",
    principleName: "Supply Chain",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Are supply chain risks for critical systems identified and documented, though management may be limited?",
    isNegative: false,
    section: "partial",
  },

  // OBJECTIVE B - Protecting Against Cyber Attack - PARTIAL
  {
    id: "B1.a.1-partial",
    outcomeId: "B1.a",
    outcomeName: "Policy, Process and Procedure Development",
    principleId: "B1",
    principleName: "Service Protection Policies and Procedures",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Are basic security policies and procedures documented, even if they're not comprehensive?",
    isNegative: false,
    section: "partial",
  },
  {
    id: "B1.b.1-partial",
    outcomeId: "B1.b",
    outcomeName: "Policy, Process and Procedure Implementation",
    principleId: "B1",
    principleName: "Service Protection Policies and Procedures",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Are security policies and procedures generally followed, with occasional exceptions?",
    isNegative: false,
    section: "partial",
  },
  {
    id: "B2.a.1-partial",
    outcomeId: "B2.a",
    outcomeName: "Identity Verification, Authentication and Authorisation",
    principleId: "B2",
    principleName: "Identity and Access Control",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Are basic identity verification processes in place, though they may not be comprehensive?",
    isNegative: false,
    section: "partial",
  },
  {
    id: "B2.b.1-partial",
    outcomeId: "B2.b",
    outcomeName: "Device Management",
    principleId: "B2",
    principleName: "Identity and Access Control",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Are devices accessing systems tracked and managed to some degree?",
    isNegative: false,
    section: "partial",
  },
  {
    id: "B2.c.1-partial",
    outcomeId: "B2.c",
    outcomeName: "Privileged User Management",
    principleId: "B2",
    principleName: "Identity and Access Control",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Are privileged accounts identified and given some additional controls?",
    isNegative: false,
    section: "partial",
  },
  {
    id: "B2.d.1-partial",
    outcomeId: "B2.d",
    outcomeName: "Identity & Access Management (IdAM)",
    principleId: "B2",
    principleName: "Identity and Access Control",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Is there a basic identity and access management system in place?",
    isNegative: false,
    section: "partial",
  },
  {
    id: "B3.a.1-partial",
    outcomeId: "B3.a",
    outcomeName: "Understanding Data",
    principleId: "B3",
    principleName: "Data Security",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Is sensitive data identified and categorised to some degree?",
    isNegative: false,
    section: "partial",
  },
  {
    id: "B3.b.1-partial",
    outcomeId: "B3.b",
    outcomeName: "Data in Transit",
    principleId: "B3",
    principleName: "Data Security",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Is data in transit protected with basic encryption for sensitive information?",
    isNegative: false,
    section: "partial",
  },
  {
    id: "B3.c.1-partial",
    outcomeId: "B3.c",
    outcomeName: "Stored Data",
    principleId: "B3",
    principleName: "Data Security",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Is stored sensitive data protected with encryption and access controls to some degree?",
    isNegative: false,
    section: "partial",
  },
  {
    id: "B3.d.1-partial",
    outcomeId: "B3.d",
    outcomeName: "Mobile Data",
    principleId: "B3",
    principleName: "Data Security",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Are mobile devices that access sensitive data subject to basic security controls?",
    isNegative: false,
    section: "partial",
  },
  {
    id: "B4.a.1-partial",
    outcomeId: "B4.a",
    outcomeName: "Secure By Design",
    principleId: "B4",
    principleName: "Resilient Networks and Systems",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Are security considerations included in system design discussions?",
    isNegative: false,
    section: "partial",
  },
  {
    id: "B4.b.1-partial",
    outcomeId: "B4.b",
    outcomeName: "Secure Configuration",
    principleId: "B4",
    principleName: "Resilient Networks and Systems",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Are systems configured with basic security hardening applied?",
    isNegative: false,
    section: "partial",
  },
  {
    id: "B4.c.1-partial",
    outcomeId: "B4.c",
    outcomeName: "Secure Management",
    principleId: "B4",
    principleName: "Resilient Networks and Systems",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Are systems managed with basic security practices in place?",
    isNegative: false,
    section: "partial",
  },
  {
    id: "B4.d.1-partial",
    outcomeId: "B4.d",
    outcomeName: "Vulnerability Management",
    principleId: "B4",
    principleName: "Resilient Networks and Systems",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Are vulnerabilities tracked and remediated, though timescales may not always be met?",
    isNegative: false,
    section: "partial",
  },
  {
    id: "B5.a.1-partial",
    outcomeId: "B5.a",
    outcomeName: "Resilience Preparation",
    principleId: "B5",
    principleName: "Resilient Networks and Systems",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Are basic resilience measures planned and documented?",
    isNegative: false,
    section: "partial",
  },
  {
    id: "B5.b.1-partial",
    outcomeId: "B5.b",
    outcomeName: "Design for Resilience",
    principleId: "B5",
    principleName: "Resilient Networks and Systems",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Are systems designed with some resilience features incorporated?",
    isNegative: false,
    section: "partial",
  },
  {
    id: "B5.c.1-partial",
    outcomeId: "B5.c",
    outcomeName: "Backups",
    principleId: "B5",
    principleName: "Resilient Networks and Systems",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Are backups performed regularly for key systems, though coverage or testing may be limited?",
    isNegative: false,
    section: "partial",
  },
  {
    id: "B6.a.1-partial",
    outcomeId: "B6.a",
    outcomeName: "Cyber Security Culture",
    principleId: "B6",
    principleName: "Staff Awareness and Training",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Are security awareness activities conducted, even if not comprehensive?",
    isNegative: false,
    section: "partial",
  },
  {
    id: "B6.b.1-partial",
    outcomeId: "B6.b",
    outcomeName: "Cyber Security Training",
    principleId: "B6",
    principleName: "Staff Awareness and Training",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Is basic security training provided to staff, though it may not be role-specific?",
    isNegative: false,
    section: "partial",
  },

  // OBJECTIVE C - Detecting Cyber Security Events - PARTIAL
  {
    id: "C1.a.1-partial",
    outcomeId: "C1.a",
    outcomeName: "Sources and Tools for Logging and Monitoring",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Is security-related data collected from key systems, though coverage may not be comprehensive?",
    isNegative: false,
    section: "partial",
  },
  {
    id: "C1.b.1-partial",
    outcomeId: "C1.b",
    outcomeName: "Securing Logs",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Are logs protected with basic security controls and retention policies?",
    isNegative: false,
    section: "partial",
  },
  {
    id: "C1.c.1-partial",
    outcomeId: "C1.c",
    outcomeName: "Generating Alerts",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Are basic security alerts generated for known threat indicators?",
    isNegative: false,
    section: "partial",
  },
  {
    id: "C1.d.1-partial",
    outcomeId: "C1.d",
    outcomeName: "Triage of Security Alerts",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Are security alerts reviewed and triaged, though processes may be informal?",
    isNegative: false,
    section: "partial",
  },
  {
    id: "C1.e.1-partial",
    outcomeId: "C1.e",
    outcomeName: "Personnel Skills for Monitoring Tools and Detection",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Are personnel assigned to monitoring with basic security skills?",
    isNegative: false,
    section: "partial",
  },
  {
    id: "C1.f.1-partial",
    outcomeId: "C1.f",
    outcomeName: "Understanding User's and System's Behaviour, and Threat Intelligence",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Is some threat intelligence consumed and basic behavioral analysis performed?",
    isNegative: false,
    section: "partial",
  },
  {
    id: "C2.a.1-partial",
    outcomeId: "C2.a",
    outcomeName: "Threat Hunting",
    principleId: "C2",
    principleName: "Threat Hunting",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Are basic threat hunting activities conducted occasionally, though they may not be systematic or well-resourced?",
    isNegative: false,
    section: "partial",
  },

  // OBJECTIVE D - Minimising the Impact of Cyber Security Incidents - PARTIAL
  {
    id: "D1.a.1-partial",
    outcomeId: "D1.a",
    outcomeName: "Response Plan",
    principleId: "D1",
    principleName: "Response and Recovery Planning",
    objectiveId: "D",
    objectiveName: "Minimising the Impact of Cyber Security Incidents",
    question: "Is a basic incident response plan documented, though it may not cover all scenarios?",
    isNegative: false,
    section: "partial",
  },
  {
    id: "D1.b.1-partial",
    outcomeId: "D1.b",
    outcomeName: "Response and Recovery Capability",
    principleId: "D1",
    principleName: "Response and Recovery Planning",
    objectiveId: "D",
    objectiveName: "Minimising the Impact of Cyber Security Incidents",
    question: "Are basic response resources and capabilities identified and available?",
    isNegative: false,
    section: "partial",
  },
  {
    id: "D1.c.1-partial",
    outcomeId: "D1.c",
    outcomeName: "Testing and Exercising",
    principleId: "D1",
    principleName: "Response and Recovery Planning",
    objectiveId: "D",
    objectiveName: "Minimising the Impact of Cyber Security Incidents",
    question: "Are incident response exercises conducted occasionally, though not systematically?",
    isNegative: false,
    section: "partial",
  },
  {
    id: "D2.a.1-partial",
    outcomeId: "D2.a",
    outcomeName: "Post Incident Analysis",
    principleId: "D2",
    principleName: "Lessons Learned",
    objectiveId: "D",
    objectiveName: "Minimising the Impact of Cyber Security Incidents",
    question: "Are incidents reviewed after the fact, though root cause analysis may be limited?",
    isNegative: false,
    section: "partial",
  },
  {
    id: "D2.b.1-partial",
    outcomeId: "D2.b",
    outcomeName: "Using Incidents to Drive Improvements",
    principleId: "D2",
    principleName: "Lessons Learned",
    objectiveId: "D",
    objectiveName: "Minimising the Impact of Cyber Security Incidents",
    question: "Are some improvements made following incidents, though not consistently implemented?",
    isNegative: false,
    section: "partial",
  },

  // ACHIEVED QUESTIONS
  // OBJECTIVE A - Managing Security Risk
  {
    id: "A1.a.1-achieved",
    outcomeId: "A1.a",
    outcomeName: "Board Direction",
    principleId: "A1",
    principleName: "Governance",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Is the security of network and information systems discussed and reported on regularly at board-level with comprehensive, expert-supported information?",
    isNegative: false,
    section: "achieved",
  },
  {
    id: "A1.a.2-achieved",
    outcomeId: "A1.a",
    outcomeName: "Board Direction",
    principleId: "A1",
    principleName: "Governance",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Are board-level discussions on security based on current, complete information with clear expert guidance and analysis?",
    isNegative: false,
    section: "achieved",
  },
  {
    id: "A1.b.1-achieved",
    outcomeId: "A1.b",
    outcomeName: "Roles and Responsibilities",
    principleId: "A1",
    principleName: "Governance",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Are all key security roles clearly defined, filled, and provided with adequate authority and resources?",
    isNegative: false,
    section: "achieved",
  },
  {
    id: "A1.c.1-achieved",
    outcomeId: "A1.c",
    outcomeName: "Decision-making",
    principleId: "A1",
    principleName: "Governance",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Are security decisions made by appropriate parties with clear accountability and documented rationale?",
    isNegative: false,
    section: "achieved",
  },
  {
    id: "A2.a.1-achieved",
    outcomeId: "A2.a",
    outcomeName: "Risk Management Process",
    principleId: "A2",
    principleName: "Risk Management",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Are security risks to essential functions comprehensively identified, assessed, documented, and regularly reviewed?",
    isNegative: false,
    section: "achieved",
  },
  {
    id: "A2.b.1-achieved",
    outcomeId: "A2.b",
    outcomeName: "Understanding Threat",
    principleId: "A2",
    principleName: "Risk Management",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Is comprehensive threat analysis performed regularly with clearly defined threat assumptions and current threat intelligence?",
    isNegative: false,
    section: "achieved",
  },
  {
    id: "A2.c.1-achieved",
    outcomeId: "A2.c",
    outcomeName: "Assurance",
    principleId: "A2",
    principleName: "Risk Management",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Are comprehensive assurance methods applied with clear understanding of their strengths and limitations, and results appropriately validated?",
    isNegative: false,
    section: "achieved",
  },
  {
    id: "A3.a.1-achieved",
    outcomeId: "A3.a",
    outcomeName: "Asset Management",
    principleId: "A3",
    principleName: "Asset Management",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Are comprehensive, current asset inventories maintained covering all domains with documented dependencies and appropriate retention policies?",
    isNegative: false,
    section: "achieved",
  },
  {
    id: "A4.a.1-achieved",
    outcomeId: "A4.a",
    outcomeName: "Supply Chain",
    principleId: "A4",
    principleName: "Supply Chain",
    objectiveId: "A",
    objectiveName: "Managing Security Risk",
    question: "Are supply chain risks comprehensively managed with clear visibility of sub-contractors, contractual security obligations, and understanding of data handling?",
    isNegative: false,
    section: "achieved",
  },

  // OBJECTIVE B - Protecting Against Cyber Attack - ACHIEVED
  {
    id: "B1.a.1-achieved",
    outcomeId: "B1.a",
    outcomeName: "Policy, Process and Procedure Development",
    principleId: "B1",
    principleName: "Service Protection Policies and Procedures",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Are comprehensive, current security policies and procedures documented, maintained, and applied universally?",
    isNegative: false,
    section: "achieved",
  },
  {
    id: "B1.b.1-achieved",
    outcomeId: "B1.b",
    outcomeName: "Policy, Process and Procedure Implementation",
    principleId: "B1",
    principleName: "Service Protection Policies and Procedures",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Are security policies and procedures consistently followed with clear understanding of how they support essential functions?",
    isNegative: false,
    section: "achieved",
  },
  {
    id: "B2.a.1-achieved",
    outcomeId: "B2.a",
    outcomeName: "Identity Verification, Authentication and Authorisation",
    principleId: "B2",
    principleName: "Identity and Access Control",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Are robust identity verification and authentication controls implemented with appropriate multi-factor authentication?",
    isNegative: false,
    section: "achieved",
  },
  {
    id: "B2.b.1-achieved",
    outcomeId: "B2.b",
    outcomeName: "Device Management",
    principleId: "B2",
    principleName: "Identity and Access Control",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Are all devices comprehensively managed with full visibility and security controls?",
    isNegative: false,
    section: "achieved",
  },
  {
    id: "B2.c.1-achieved",
    outcomeId: "B2.c",
    outcomeName: "Privileged User Management",
    principleId: "B2",
    principleName: "Identity and Access Control",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Are privileged accounts fully controlled with enhanced monitoring, just-in-time access, and strict accountability?",
    isNegative: false,
    section: "achieved",
  },
  {
    id: "B2.d.1-achieved",
    outcomeId: "B2.d",
    outcomeName: "Identity & Access Management (IdAM)",
    principleId: "B2",
    principleName: "Identity and Access Control",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Is there a comprehensive identity and access management system with centralized control and regular access reviews?",
    isNegative: false,
    section: "achieved",
  },
  {
    id: "B3.a.1-achieved",
    outcomeId: "B3.a",
    outcomeName: "Understanding Data",
    principleId: "B3",
    principleName: "Data Security",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Is all data comprehensively classified with clear handling requirements understood and followed?",
    isNegative: false,
    section: "achieved",
  },
  {
    id: "B3.b.1-achieved",
    outcomeId: "B3.b",
    outcomeName: "Data in Transit",
    principleId: "B3",
    principleName: "Data Security",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Is all data in transit protected with strong encryption appropriate to its classification?",
    isNegative: false,
    section: "achieved",
  },
  {
    id: "B3.c.1-achieved",
    outcomeId: "B3.c",
    outcomeName: "Stored Data",
    principleId: "B3",
    principleName: "Data Security",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Is all stored data protected with comprehensive encryption and access controls appropriate to its classification?",
    isNegative: false,
    section: "achieved",
  },
  {
    id: "B3.d.1-achieved",
    outcomeId: "B3.d",
    outcomeName: "Mobile Data",
    principleId: "B3",
    principleName: "Data Security",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Are mobile devices fully managed with comprehensive security controls including encryption and remote wipe?",
    isNegative: false,
    section: "achieved",
  },
  {
    id: "B4.a.1-achieved",
    outcomeId: "B4.a",
    outcomeName: "Secure By Design",
    principleId: "B4",
    principleName: "Resilient Networks and Systems",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Are systems designed with security as a core requirement from inception with threat modeling and secure architecture?",
    isNegative: false,
    section: "achieved",
  },
  {
    id: "B4.b.1-achieved",
    outcomeId: "B4.b",
    outcomeName: "Secure Configuration",
    principleId: "B4",
    principleName: "Resilient Networks and Systems",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Are all systems hardened following industry standards with regular configuration audits?",
    isNegative: false,
    section: "achieved",
  },
  {
    id: "B4.c.1-achieved",
    outcomeId: "B4.c",
    outcomeName: "Secure Management",
    principleId: "B4",
    principleName: "Resilient Networks and Systems",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Are systems managed securely with comprehensive change control, secure administration practices, and regular security reviews?",
    isNegative: false,
    section: "achieved",
  },
  {
    id: "B4.d.1-achieved",
    outcomeId: "B4.d",
    outcomeName: "Vulnerability Management",
    principleId: "B4",
    principleName: "Resilient Networks and Systems",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Are vulnerabilities comprehensively identified, assessed, and remediated within defined timescales based on severity?",
    isNegative: false,
    section: "achieved",
  },
  {
    id: "B5.a.1-achieved",
    outcomeId: "B5.a",
    outcomeName: "Resilience Preparation",
    principleId: "B5",
    principleName: "Resilient Networks and Systems",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Are comprehensive resilience measures implemented with regular testing and clear recovery procedures?",
    isNegative: false,
    section: "achieved",
  },
  {
    id: "B5.b.1-achieved",
    outcomeId: "B5.b",
    outcomeName: "Design for Resilience",
    principleId: "B5",
    principleName: "Resilient Networks and Systems",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Are systems designed with comprehensive resilience features including redundancy, failover, and graceful degradation?",
    isNegative: false,
    section: "achieved",
  },
  {
    id: "B5.c.1-achieved",
    outcomeId: "B5.c",
    outcomeName: "Backups",
    principleId: "B5",
    principleName: "Resilient Networks and Systems",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Are comprehensive, automatic, and regularly tested backups secured at multiple sites with full coverage of all critical data?",
    isNegative: false,
    section: "achieved",
  },
  {
    id: "B6.a.1-achieved",
    outcomeId: "B6.a",
    outcomeName: "Cyber Security Culture",
    principleId: "B6",
    principleName: "Staff Awareness and Training",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Is a strong security culture established with comprehensive awareness programs and engaged leadership?",
    isNegative: false,
    section: "achieved",
  },
  {
    id: "B6.b.1-achieved",
    outcomeId: "B6.b",
    outcomeName: "Cyber Security Training",
    principleId: "B6",
    principleName: "Staff Awareness and Training",
    objectiveId: "B",
    objectiveName: "Protecting Against Cyber Attack",
    question: "Is comprehensive, role-specific security training provided to all staff with regular refreshers and assessments?",
    isNegative: false,
    section: "achieved",
  },

  // OBJECTIVE C - Detecting Cyber Security Events - ACHIEVED
  {
    id: "C1.a.1-achieved",
    outcomeId: "C1.a",
    outcomeName: "Sources and Tools for Logging and Monitoring",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Is comprehensive security data collected from all critical systems with appropriate tools and coverage?",
    isNegative: false,
    section: "achieved",
  },
  {
    id: "C1.b.1-achieved",
    outcomeId: "C1.b",
    outcomeName: "Securing Logs",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Are logs fully secured with strong integrity controls, encryption, and appropriate retention policies?",
    isNegative: false,
    section: "achieved",
  },
  {
    id: "C1.c.1-achieved",
    outcomeId: "C1.c",
    outcomeName: "Generating Alerts",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Are comprehensive, prioritized security alerts generated with enrichment and correlation capabilities?",
    isNegative: false,
    section: "achieved",
  },
  {
    id: "C1.d.1-achieved",
    outcomeId: "C1.d",
    outcomeName: "Triage of Security Alerts",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Are security alerts systematically triaged with documented procedures, clear categorization, and full record-keeping?",
    isNegative: false,
    section: "achieved",
  },
  {
    id: "C1.e.1-achieved",
    outcomeId: "C1.e",
    outcomeName: "Personnel Skills for Monitoring Tools and Detection",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Are monitoring personnel fully skilled with comprehensive training, clear understanding of essential functions, and appropriate workload?",
    isNegative: false,
    section: "achieved",
  },
  {
    id: "C1.f.1-achieved",
    outcomeId: "C1.f",
    outcomeName: "Understanding User's and System's Behaviour, and Threat Intelligence",
    principleId: "C1",
    principleName: "Security Monitoring",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Is threat intelligence comprehensively integrated with strong understanding of normal behavior and effective anomaly detection?",
    isNegative: false,
    section: "achieved",
  },
  {
    id: "C2.a.1-achieved",
    outcomeId: "C2.a",
    outcomeName: "Threat Hunting",
    principleId: "C2",
    principleName: "Threat Hunting",
    objectiveId: "C",
    objectiveName: "Detecting Cyber Security Events",
    question: "Are comprehensive, structured threat hunting activities conducted systematically with well-trained personnel, documented procedures, and clear records of findings?",
    isNegative: false,
    section: "achieved",
  },

  // OBJECTIVE D - Minimising the Impact of Cyber Security Incidents - ACHIEVED
  {
    id: "D1.a.1-achieved",
    outcomeId: "D1.a",
    outcomeName: "Response Plan",
    principleId: "D1",
    principleName: "Response and Recovery Planning",
    objectiveId: "D",
    objectiveName: "Minimising the Impact of Cyber Security Incidents",
    question: "Is a comprehensive, regularly tested incident response plan documented and well-understood by all relevant staff?",
    isNegative: false,
    section: "achieved",
  },
  {
    id: "D1.b.1-achieved",
    outcomeId: "D1.b",
    outcomeName: "Response and Recovery Capability",
    principleId: "D1",
    principleName: "Response and Recovery Planning",
    objectiveId: "D",
    objectiveName: "Minimising the Impact of Cyber Security Incidents",
    question: "Are comprehensive response resources, capabilities, and backup mechanisms in place and regularly tested?",
    isNegative: false,
    section: "achieved",
  },
  {
    id: "D1.c.1-achieved",
    outcomeId: "D1.c",
    outcomeName: "Testing and Exercising",
    principleId: "D1",
    principleName: "Response and Recovery Planning",
    objectiveId: "D",
    objectiveName: "Minimising the Impact of Cyber Security Incidents",
    question: "Are incident response exercises conducted regularly and systematically with outputs fed into lessons learned?",
    isNegative: false,
    section: "achieved",
  },
  {
    id: "D2.a.1-achieved",
    outcomeId: "D2.a",
    outcomeName: "Post Incident Analysis",
    principleId: "D2",
    principleName: "Lessons Learned",
    objectiveId: "D",
    objectiveName: "Minimising the Impact of Cyber Security Incidents",
    question: "Is comprehensive root cause analysis performed for all incidents with formal investigation processes?",
    isNegative: false,
    section: "achieved",
  },
  {
    id: "D2.b.1-achieved",
    outcomeId: "D2.b",
    outcomeName: "Using Incidents to Drive Improvements",
    principleId: "D2",
    principleName: "Lessons Learned",
    objectiveId: "D",
    objectiveName: "Minimising the Impact of Cyber Security Incidents",
    question: "Are improvements from lessons learned consistently implemented with appropriate organisational priority and testing?",
    isNegative: false,
    section: "achieved",
  },
];

export interface AssessmentResponse {
  questionId: string;
  response: boolean | null; // true = yes, false = no, null = not answered
}

export interface ProjectAssessment {
  id: string;
  projectId: string;
  responses: AssessmentResponse[];
  completedAt?: string;
  createdAt: string;
  updatedAt: string;
}

export const calculateComplianceScore = (responses: AssessmentResponse[]): {
  total: number;
  answered: number;
  compliant: number;
  nonCompliant: number;
  percentage: number;
} => {
  const total = CAF_ASSESSMENT_QUESTIONS.length;
  const answered = responses.filter((r) => r.response !== null).length;
  
  // For negative questions (isNegative = true), "No" means compliant
  // For positive questions (isNegative = false), "Yes" means compliant
  const compliant = responses.filter((r) => {
    if (r.response === null) return false;
    const question = CAF_ASSESSMENT_QUESTIONS.find((q) => q.id === r.questionId);
    if (!question) return false;
    
    return question.isNegative ? r.response === false : r.response === true;
  }).length;
  
  const nonCompliant = answered - compliant;
  const percentage = answered > 0 ? Math.round((compliant / answered) * 100) : 0;
  
  return {
    total,
    answered,
    compliant,
    nonCompliant,
    percentage,
  };
};

export const getOutcomeCompliance = (
  outcomeId: string,
  responses: AssessmentResponse[]
): {
  total: number;
  answered: number;
  compliant: number;
  percentage: number;
} => {
  const outcomeQuestions = CAF_ASSESSMENT_QUESTIONS.filter(
    (q) => q.outcomeId === outcomeId
  );
  const outcomeResponses = responses.filter((r) =>
    outcomeQuestions.some((q) => q.id === r.questionId)
  );
  
  const total = outcomeQuestions.length;
  const answered = outcomeResponses.filter((r) => r.response !== null).length;
  
  const compliant = outcomeResponses.filter((r) => {
    if (r.response === null) return false;
    const question = outcomeQuestions.find((q) => q.id === r.questionId);
    if (!question) return false;
    
    return question.isNegative ? r.response === false : r.response === true;
  }).length;
  
  const percentage = answered > 0 ? Math.round((compliant / answered) * 100) : 0;
  
  return {
    total,
    answered,
    compliant,
    percentage,
  };
};
